services:
  - type: web
    name: social-network-api
    env: node
    rootDir: server
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: APP_ENV
        value: production
